"""added second table

Revision ID: fd7a8bf81c1b
Revises: d18b036e8cfc
Create Date: 2022-10-28 00:09:00.352452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7a8bf81c1b'
down_revision = 'd18b036e8cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_tabl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reg_nomer', sa.String(), nullable=True),
    sa.Column('date_postup', sa.Date(), nullable=True),
    sa.Column('name_doc', sa.String(), nullable=True),
    sa.Column('story_doc', sa.String(), nullable=True),
    sa.Column('foiv', sa.String(), nullable=True),
    sa.Column('cur_aprf', sa.String(), nullable=True),
    sa.Column('napr', sa.String(), nullable=True),
    sa.Column('fed_num', sa.String(), nullable=True),
    sa.Column('type_of_doc', sa.String(), nullable=True),
    sa.Column('resh_doc', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('fin_oc', sa.String(), nullable=True),
    sa.Column('exp_oc', sa.String(), nullable=True),
    sa.Column('req_otv', sa.String(), nullable=True),
    sa.Column('date_otv', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    conn = op.get_bind()
    a = None
    conn.execute('''
            insert into public.second_tabl (reg_nomer, date_postup, name_doc, story_doc, foiv, cur_aprf, napr, fed_num, type_of_doc, resh_doc, status, fin_oc, exp_oc, req_otv, date_otv)
            values  (NULL, NULL, NULL, NULL,'Федеральный фонд обязательного медицинского страхования', 'Иванов', '1', '1', '1', NULL, NULL, NULL, NULL, NULL, NULL),
                    (NULL, NULL, NULL, NULL, 'МВД России', 'Курочкин', '2', '2', '2', NULL, NULL, NULL, NULL, NULL, NULL),
                    (NULL, NULL, NULL, NULL, 'Рослесхоз', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
        ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('second_tabl')
    # ### end Alembic commands ###
